### ISSUE TITLE
Refill on start doesn't work consistently

### ISSUE THREAD

**Issue by FullStackForger** [qiankanglai/LoopScrollRect#21]
Refilling scroll rect  on start is not consistent. 
ScrollRect sometimes is populated on start and sometimes it is not.

I looked at demo and noticed in your examples 1st VerticalSCroll object get's auto populated on start, others require InitOnStartScript.  It becomes even more confusing due to the fact that both scrolls VerticalScroll and VerticalScroll_Reverse have exactly the same properties in inspector (apart of Reverse Direction toggle.

**Comment by qiankanglai** [comment]
Sorry for late reply (quite busy working on my projects recently)

1st `VerticalScroll` can auto populate because it can be filled from top to bottom. So this one will try to fill it _if it is able to_. While 2nd `VerticalScroll_Reverse` can have a stable state without the need to fill, and I have to add `InitOnStartScript`. 

I think that adding `InitOnStartScript` on all Scrolls will be less confusing.

For Vertical/HorizontalScroll and the reversed version, there are two differences:
- Reverse Direction toggle
- Its corresponding `Content` has Different Anchors
![image](https://user-images.githubusercontent.com/1546130/32760464-0b8149c8-c8b4-11e7-8db8-591d641e757b.png)
![image](https://user-images.githubusercontent.com/1546130/32760473-1156e1be-c8b4-11e7-9b48-be01bc15cb21.png)

**Comment by FullStackForger** [comment]
Thanks for the replay. Appreciated. Yes. It makes sense now. It is great library. I am planning to re-implement pooling for my own use with Zenject but other than that already making use of it. I think it would be awesome to have some sort of pooling interface scroller is using instead of concrete class. I have your repository forked so will give you a shout when and if ;) came up with something good. Thanks again! :)

**Comment by qiankanglai** [comment]
Thanks a lot and any PR is welcomed. We have used this library in several projects in our company and hope it helps.
