### ISSUE TITLE
Can GridLayout contain different items width and height?

### ISSUE THREAD

**Issue by ProgrammingLife** [qiankanglai/LoopScrollRect#66]
I need GridLayout with some subtitles (headers). So I thought I could make something like this:

```
Text Caption1:
image1 | image2 | image3
image4 | image5 | image6

Text Caption2:
image7 | image8 | image9

Text Caption3:
...
```

How can I get it? :)

**Comment by qiankanglai** [comment]
For this case, I suggest you using Vertical Layout, and every line may contain one text caption or three images. Since you can fill different data into every cell, it is up to you to support customize layou.

Since GridLayout cannot support "new line" after "Text Captaion1", it will be annoying using this way
