### ISSUE TITLE
about start of the system

### ISSUE THREAD

**Issue by viol3** [qiankanglai/LoopScrollRect#78]
Hello. Your script is awesome and really useful for my project. But I need to notify it, you need to start "InitOnStart" functions with delay. Otherwise with stretch anchor recttransforms, rect.width or rect.height will be negative and system won't fill elements at Start. I have fixed this issue by running "InitOnStart" functions with 0.1f delay.

**Comment by qiankanglai** [comment]
Sorry for late reply
This case happens when rect size is not prepared when `Start()` happens, like what you said. I have encountered one bug for `sizeDelta.width=0`. 

I'll make some assert first for notification but I don't have any elegent plan yet. (0.1f as a hard coded delay is not fit for some quick animation)

**Comment by koalli** [comment]
I think this problem is caused by calling RefillCells before the layout finished.
Maybe you can fix this by calling `EnsureLayoutHasRebuilt` before RefillCells.
