### ISSUE TITLE
LoopHorizontalScrollRect with GridLayoutGroup and row count > 1

### ISSUE THREAD

**Issue by waitxd** [qiankanglai/LoopScrollRect#8]
Hello.

Can you please adapt your LoopScrollRect for using with horizontal GridLayoutGroup when "Fixed Row Count" > 1?

Example (short video):
https://gfycat.com/FatherlyWealthyAtlanticblackgoby

How to reproduce on demo project:
1. Replace "Horizontal Layout Group" with "Grid Layout Group" in content of "HorizontalScroll" gameobject.
2. Set "Constraint" to "Fixed Row Count".
3. Set "Constraint Count" to 2 (or more).
4. Run project.
5. Try to scroll and take a look on cell numbers.

**Comment by qiankanglai** [comment]
Got it. But I'm on vacation for about one week, so I'll check and fix a little later 😄

**Comment by qiankanglai** [comment]
Hi, I just test my code and it works well. A new example has been pushed. I guess you may miss this setting:

<img width="289" alt="wx20170128-194530 2x" src="https://cloud.githubusercontent.com/assets/1546130/22396365/064e25e8-e593-11e6-9de0-b61b1a0c9997.png">

Make sure `Start Axis` is setup correctly, since I find your GIF shows a strange order of cells with mine:

<img width="749" alt="qq20170128-195259 2x" src="https://cloud.githubusercontent.com/assets/1546130/22396387/81932960-e593-11e6-8826-83c7fb9973ef.png">

Sorry for late reply
