### ISSUE TITLE
Freezing

### ISSUE THREAD

**Issue by CucFlavius** [qiankanglai/LoopScrollRect#87]
When trying to scroll using scrollbar on large lists 
I am getting small freezes and it does increase the pool size. Is it possible to make it skip to a specific position in the data instead of generating new cells? 

 I absolutely love this plugin, thank you for it.

**Comment by qiankanglai** [comment]
Hi, sorry for late reply.

If you want jumping directly, you could call `RefillCells(offset)`. If animation is needed, you could try `SrollToCell(index, speed)`
It is hard to avoid pool increasing directly because it is calculated automatic. But you can adjust `threshold` at https://github.com/qiankanglai/LoopScrollRect/blob/master/Assets/Scripts/LoopScrollRect.cs#L539 and https://github.com/qiankanglai/LoopScrollRect/blob/master/Assets/Scripts/LoopScrollRect.cs#L606 to make it smaller.

**Comment by CucFlavius** [comment]
Thanks, this has worked perfectly, I'm controlling scrollbar manually now.
If the amount of items scrolled exceeds a certain amount I do RefillCells(position) else I call SetNormalizedPosition(scrollbarValue, 1)
